### PR TITLE
Integrate audit log

### PR DESCRIPTION
**Pull request by edmundoa**
Integrate audit log events, also adding `MapWidgetAuditEventTypes` to contain future audit log event types the plugin may support.

### CODE REVIEW

**Comment by joschi** [comment]
@edmundoa Since there are no real events warranting an audit log entry in this plugin, I'd simply close this PR without merging it.

**Comment by edmundoa** [comment]
At the very least we need to add the `NoAuditEvent` annotation to the resource, otherwise it will generate a warning on start-up. I can get rid of the rest of the code code, although I thought it was nicer to have it for consistency.

**Comment by joschi** [comment]
> At the very least we need to add the `NoAuditEvent` annotation to the resource, otherwise it will generate a warning on start-up.

Wasn't this only a temporary modification by @bernd to find possibly missing annotations? If those warnings are currently always logged, we should remove them to prevent annoying users with 3rd party plugins (which naturally won't have any audit log hooks in the beginning).

**Comment by edmundoa** [comment]
@joschi: I really don't know about that, maybe let's hold with this change until @bernd can clarify the matter.

**Comment by edmundoa** [comment]
Thinking about this again, I think we should still warn about 3rd party plugins. In the end they should be integrated with the audit log as well (even if they aren't right now). Also, most plugins will not need any changes for that, as they are inputs, outputs, or alarm callbacks.

**Comment by bernd** [comment]
agree with @edmundoa here, we should warn about missing audit event annotations because you want to know when something will not show up in the audit trail. That's why I added the `NoAuditEvent` annotation to mark things that don't modify state.

What I am not sure of is if we really want these warnings if no non-null `AuditEventSender` is bound. If nothing consumes the audit events, it might not be needed to warn about them. On the other hand plugin authors will never learn about this when they run with the standard setup.

**Comment by edmundoa** [comment]
All right, then I will clean-up the code, so the only change in the PR is the addition of `NoAuditEvent`. In that way we are covered if we want to let the warning enabled, and we can always remove it if we change our minds later on.

**Comment by joschi** [comment]
LGTM. 👍

**Comment by joschi** [comment]
@edmundoa @bernd The problem I see with this is, that the audit log plugin is a commercial add-on. As a plugin author, I wouldn't want to be forced to add "useless" annotations or even more logic to my code just to appease a commercial add-on.

**Comment by edmundoa** [comment]
@joschi That is a fair point, I guess we need to see how plugin authors react to this addition, and then decide what to do about it.

**Comment by bernd** [comment]
@joschi Technically it's not an addition for a commercial plugin but an addition to the audit event system of graylog core.

**Pull request merged**
