### PR TITLE
Add geo country field

### PR DESCRIPTION
**Pull request by s7nio**
Request: add country/city to a field #10.
Doesn't add the city name field, because there is not always present.
_No idea of the big merging block and the test doesn't run locally :/ sorry._

### CODE REVIEW

**Comment by joschi** [comment]
@s7nio Thank you for your contribution to Graylog!

Before we can accept any code from you, we need you to sign our [Contributor License Agreement](https://s3.amazonaws.com/graylog2public/Individual+Contributor+Assignment+Agreement+-+Graylog.pdf). Please send us a signed copy to hello@graylog.com so we can merge your pull request.

This is only required once, no matter how many contributions you make in the future. Thank you for helping us with this unfortunate administrative requirement!

Additionally, please rebase your branch on current `master` and try to stick to the existing code style (e. g. [spaces instead of tabs](https://www.youtube.com/watch?v=SsoOG6ZeyUI)).

**Comment by joschi** [comment]
@s7nio Any news on this?

**Comment by joschi** [comment]
@s7nio I'm closing this now due to inactivity. Feel free to open a new PR or comment on this one to reopen it.

**Comment by s7nio** [comment]
@joschi You probably do not received my e-mail. I've send few weeks ago the CLA to hello@graylog.com.

**Comment by joschi** [comment]
@s7nio Found it, thanks!

**Comment by joschi** [comment]
@s7nio Please (also) sign the CLA via CLA Assistant (we changed that some time ago over the previous PDF thing) and rebase your branch on current `master` to resolve the merge conflicts.

**Comment by s7nio** [comment]
@joschi I've changed my local git config and must fix the last two commits or the merge commit author (help.github: [commits-are-not-linked...](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user), [changing-author-info](https://help.github.com/articles/changing-author-info/))

**Comment by joschi** [comment]
@s7nio 
> But wonders.. why we have already a merge conflict of these two files?

Because they have been changed since you've created this PR.

**Comment by leftorbit23** [comment]
Looking forward to this new feature.

@s7nio Could you resolve the conflicts and merge your changes?

**Comment by edmundoa** [comment]
Closing this PR, as it was stale for a long time and we added the country field as part of #28.

Thank you for your contribution @s7nio, hopefully next time we manage to get your changes merged!

**Pull request closed without merging**
